### ISSUE TITLE
Error main.py

### ISSUE THREAD

**Issue by edsonjuniior** [XtrmJosh/tibia-teamspeak#8]
XXXX@XXXXXXXX:~/tsbot/tibia-teamspeak$ python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import TeamSpeakConnector, TibiaCrawler, os, CherryPyServer, cherrypy
  File "/home/XXX/tsbot/tibia-teamspeak/TeamSpeakConnector.py", line 1, in <module>
    import TeamSpeakReceiver, TeamSpeakSender, TeamSpeakChannelUpdater, DatabaseConnector, logg
ing, re
  File "/home/XXXX/tsbot/tibia-teamspeak/TeamSpeakReceiver.py", line 1, in <module>
    import ts3
ImportError: No module named ts3

**Comment by TheJoshGriffith** [comment]
Did you install the requirements as per the readme?

> You'll need a few pre-requesites to make this work, namely:
> 
> ts3
> configparser
> bs4
> requests
> jinja2
> cherrypy

**Comment by edsonjuniior** [comment]
yes, TS is in the same folder as main.py... where did i do the shit?

XXXX@XXXX:~/tsbot/tibia-teamspeak$ ls
CherryPyServer.py                        TeamSpeakConnector.py   __init__.py
DatabaseConnector.py                     TeamSpeakConnector.pyc  __pycache__
README.md                                TeamSpeakReceiver.py    config.ini
TeamSpeak3-Client-linux_amd64            TeamSpeakReceiver.pyc   config.ini.sample
TeamSpeak3-Client-linux_amd64-3.5.3.run  TeamSpeakSender.py      main.py
TeamSpeakChannelUpdater.py               TibiaCrawler.py         templates


python-configparser is already the newest version (3.5.0-1).
python3-bs4 is already the newest version (4.6.0-1).
python-requests is already the newest version (2.18.4-2ubuntu0.1).
python-jinja2 is already the newest version (2.10-1ubuntu0.18.04.1).
python-cherrypy is already the newest version (2.3.0-5).

**Comment by TheJoshGriffith** [comment]
You don't list ts3 in your installed packages: https://py-ts3.readthedocs.io/en/v2/installation.html

**Comment by edsonjuniior** [comment]
Successfully installed ts3-1.0.11

and the module error persists
'ImportError: No module named ts3'

**Comment by edsonjuniior** [comment]
Name: ts3
Version: 2.0.0b3
Summary: TS3 Server Query API and TS3 Client Query API
Home-page: https://github.com/benediktschmitt/py-ts3
Author: The py-ts3 authors <see AUTHORS.txt>
Author-email: UNKNOWN
License: not available
Location: /home/ediinhu/.local/lib/python3.6/site-packages
Requires: paramiko

give up! :( kkkkkkk

**Comment by edsonjuniior** [comment]
I tried to go through debian now, same thing, I install everything that asks, but when running python main.py it gives the ts3 error :(

ediinhu@vm-1:~/tibia-teamspeak$ python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import TeamSpeakConnector, TibiaCrawler, os, CherryPyServer, cherrypy
  File "/home/ediinhu/tibia-teamspeak/TeamSpeakConnector.py", line 1, in <module>
    import TeamSpeakReceiver, TeamSpeakSender, TeamSpeakChannelUpdater, DatabaseConnector, logging, re
  File "/home/ediinhu/tibia-teamspeak/TeamSpeakReceiver.py", line 1, in <module>
    import ts3
ImportError: No module named ts3

using command. pip3 list
ts3                 1.0.11

What can it be?
which operating system is ideal?

**Comment by KayzerStorm** [comment]
**I have the same problem:**

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import TeamSpeakConnector, TibiaCrawler, os, CherryPyServer, cherrypy
  File "/home/tbot/git/tibia-teamspeak/TeamSpeakConnector.py", line 1, in <module>
    import TeamSpeakReceiver, TeamSpeakSender, TeamSpeakChannelUpdater, DatabaseConnector, logging, re
  File "/home/tbot/git/tibia-teamspeak/TeamSpeakReceiver.py", line 1, in <module>
    import ts3
ImportError: No module named ts3

**I already have installed ts3 module**
